In [1]:
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from tabulate import tabulate

In [2]:
x1=np.linspace(-10,10,2001)
x2=np.linspace(-15,15,2001)
n=np.array([0.001,0.005,0.01,0.05])
x=np.array([x1,x2]).transpose()
x1,x2=np.meshgrid(x1,x2)

In [3]:
def f(x1,x2):
    return 10*x1**2 + 5*x1*x2 + 10*(x2-3)**2
def gradient(x1,x2):
    return np.array([(20*x1 + 5*x2),(5*x1 + 20*(x2-3))])

In [4]:
z=f(x1,x2)

In [5]:
print(z.shape)
print(z)

(2001, 2001)
[[4990.      4987.251   4984.504   ... 3487.504   3488.751   3490.     ]
 [4983.85225 4981.104   4978.35775 ... 3482.85475 3484.1025  3485.35225]
 [4977.709   4974.9615  4972.216   ... 3478.21    3479.4585  3480.709  ]
 ...
 [1684.309   1683.0585  1681.81    ... 3175.816   3178.5615  3181.309  ]
 [1687.15225 1685.9025  1684.65475 ... 3180.15775 3182.904   3185.65225]
 [1690.      1688.751   1687.504   ... 3184.504   3187.251   3190.     ]]


In [6]:
g=gradient(x1,x2)

In [7]:
print(g.shape)
print(g)

(2, 2001, 2001)
[[[-275.    -274.8   -274.6   ...  124.6    124.8    125.   ]
  [-274.925 -274.725 -274.525 ...  124.675  124.875  125.075]
  [-274.85  -274.65  -274.45  ...  124.75   124.95   125.15 ]
  ...
  [-125.15  -124.95  -124.75  ...  274.45   274.65   274.85 ]
  [-125.075 -124.875 -124.675 ...  274.525  274.725  274.925]
  [-125.    -124.8   -124.6   ...  274.6    274.8    275.   ]]

 [[-410.    -409.95  -409.9   ... -310.1   -310.05  -310.   ]
  [-409.7   -409.65  -409.6   ... -309.8   -309.75  -309.7  ]
  [-409.4   -409.35  -409.3   ... -309.5   -309.45  -309.4  ]
  ...
  [ 189.4    189.45   189.5   ...  289.3    289.35   289.4  ]
  [ 189.7    189.75   189.8   ...  289.6    289.65   289.7  ]
  [ 190.     190.05   190.1   ...  289.9    289.95   290.   ]]]


In [8]:
# fig=plt.figure()
# ax=fig.add_subplot(111,projection='3d')
# ax.plot_surface(x1,x2,z,cmap='jet')

In [9]:
# fig=plt.figure()
# ax=fig.add_subplot(111,projection='3d')
# ax.plot_surface(x1,x2,g[0],cmap='jet')

In [10]:
x1min=np.zeros(4)
x2min=np.zeros(4)
iterations_arr=np.zeros(4)
f_value=np.zeros(4)

In [11]:
np.linalg.norm(gradient(x1[0][460],x2[588][0]))

252.28073648219754

In [12]:
for i in np.arange(len(n)):
    iterations=0
    xm=np.array([x1[0][0],x2[0][0]])
    for j in np.arange(len(x1)):
        if(x1[0][j]>=-10 and x1[0][j]<=10):
            x1[0][j]=x1[0][j]+n[i]*x1[0][j]
            for k in np.arange(len(x2)):
                if(x2[k][0]>=-15 and x2[k][0]<=15):
                    x2[k][0]=x2[k][0]+n[i]*x2[k][0]
                    iterations=iterations+1
                    xm=abs(gradient(x1[0][j],x2[k][0]))
                    print(n[i],x1[0][j],x2[k][0],xm,np.linalg.norm(xm))
                    if(np.linalg.norm(xm)<0.001):
                        x1min[i]=x1[0][j]
                        x2min[i]=x2[k][0]
                        iterations_arr[i]=iterations
                        f_value=f(x1[0][j],x2[k][0])
                        break
            if(np.linalg.norm(xm)<0.001):
                break

0.001 -10.01 -15.015 [275.275 410.35 ] 494.12897924023844
0.001 -10.01 -14.999984999999999 [275.199925 410.0497  ] 493.83778226265315
0.001 -10.01 -14.98497 [275.12485 409.7494 ] 493.54660761460264
0.001 -10.01 -14.969955 [275.049775 409.4491  ] 493.255455335631
0.001 -10.01 -14.954939999999999 [274.9747 409.1488] 492.9643254653728
0.001 -10.01 -14.939925 [274.899625 408.8485  ] 492.67321804355333
0.001 -10.01 -14.92491 [274.82455 408.5482 ] 492.38213310998856
0.001 -10.01 -14.909894999999999 [274.749475 408.2479  ] 492.0910707045857
0.001 -10.01 -14.89488 [274.6744 407.9476] 491.8000308673435
0.001 -10.01 -14.879865 [274.599325 407.6473  ] 491.509013638352
0.001 -10.01 -14.864849999999999 [274.52425 407.347  ] 491.2180190577932
0.001 -10.01 -14.849835 [274.449175 407.0467  ] 490.92704716594153
0.001 -10.01 -14.83482 [274.3741 406.7464] 490.6360980031637
0.001 -10.01 -14.819805 [274.299025 406.4461  ] 490.34517160991874
0.001 -10.01 -14.804789999999999 [274.22395 406.1458 ] 490.0542680

In [13]:
data=list(zip(n,iterations_arr,x1min,x2min,f_value))
header=["Step Size","Iterations","x1","x2","Function Value"]
table=tabulate(data,header)
print(table)

  Step Size    Iterations    x1    x2    Function Value
-----------  ------------  ----  ----  ----------------
      0.001             0     0     0                 0
      0.005             0     0     0                 0
      0.01              0     0     0                 0
      0.05              0     0     0                 0
